#!/usr/bin/env bash
#displays information about subdomains

display_info () {
    #address=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -1)
    #type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | head -1)
    dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

display_info "$1" "www"
display_info "$1" "lb-01"
display_info "$1" "web-01"
display_info "$1" "web-02"
