#!/usr/bin/env bash
#Install your load balancer

apt update
apt install -y haproxy=1.6.\*

printf %s "
    balance roundrobin
    server 2795-web-01 34.138.206.129:80
    server 2795-web-02 35.231.142.0:80
" >> /etc/haproxy/haproxy.cfg

service haproxy start
