#!/usr/bin/env bash
# displays "To infinity and beyond indefinitely" with a sleep 2 in between each iteration and "I am invincible!!!" when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' SIGTERM
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
