#!/usr/bin/env bash
# gives you information about the holbertonschool file using the if/else statement

file="holbertonschool"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
	then
		echo "holbertonschool file is not empty"
    else
		echo "holbertonschool file is empty"
    fi
    if [ -f "$file" ]
	then
		echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
